# 簡易なVerilogシミュレーション＆波形表示Jupyterノートブック
三浦克介 <miura.katsuyoshi@gmail.com>
v1.0, 2021-06-13
:imagesdir: README_Images
:homepage: https://github.com/miura-katsuyoshi/yurubinoya_schedule_display
:toc: left
:sectnums:
:toclevels: 3
:xrefstyle: short
:icons: font
:appendix-caption: 付録
:caution-caption: 注意
:example-caption: 例
:figure-caption: 図
:important-caption: 重要
:last-update-label: 最終更新
:listing-caption: リスト
:note-caption: 備考
:table-caption: 表
:toc-title: 目次
:warning-caption: 警告

https://colab.research.google.com/github/miura-katsuyoshi/VerilogSimulation.ipynb/blob/main/VerilogSimulation.ipynb[Matplotlib でグラフ表示（Google Colaboratory で表示）]

https://colab.research.google.com/github/miura-katsuyoshi/VerilogSimulation.ipynb/blob/main/Verilog2WaveDrome.ipynb[WaveDrome でグラフ表示（Google Colaboratory で表示）]

## 概要

http://iverilog.icarus.com/[Icarus Verilog (iverilog)] でコンパイル＆実行し、 https://matplotlib.org/[Matplotlib] あるいは https://wavedrom.com/[WaveDrome] で波形表示する、Verilog HDL の簡易シミュレーション＆波形表示 Jupyter ノートブックです。

Google Colaboratory 上で、Verilog シミュレーションして、波形表示できます。実行するには、Google アカウントでのログインが必要です。

## 使い方

. いずれかのノートブックを、Google Colaboratory で開きます。
** https://colab.research.google.com/github/miura-katsuyoshi/VerilogSimulation.ipynb/blob/main/VerilogSimulation.ipynb[Matplotlib でグラフ表示（Google Colaboratory で表示）]
** https://colab.research.google.com/github/miura-katsuyoshi/VerilogSimulation.ipynb/blob/main/Verilog2WaveDrome.ipynb[WaveDrome でグラフ表示（Google Colaboratory で表示）]

. ファイル -> ドライブにコピーを保存。
+
NOTE: Google アカウントでのログインを求められます（未ログインの場合）。

. 最初のコードセルを実行し、 http://iverilog.icarus.com/[Icarus Verilog (iverilog)] をインストールします。

. 2番目のコードセルの `verilog_source = """` から `"""` の間に、Verilog ソースコードを記述します。
+
本ツールで波形表示するためには、決められた書式でログを出力する必要があります。詳しくは、 <<sec:verilogFormat>> を参照してください。

. 2番目のコードセルを実行し、シミュレーションを実行します。
+
NOTE: エラーが出た場合は、エラーメッセージをよく読んで、Verilog ソースコードを修正してください。

. 3番目のコードセルを実行すると、Matplotlib 版では、セルの下側に波形が表示されます。WaveDrome 版ではリンクが表示されます。リンクをクリックすると、WaveDrome のサイトに飛び、波形が表示されます。

[[sec:verilogFormat]]
## 波形表示用の Verilog の記述のし方

### Matplotlib でグラフを描く場合

initial ブロックの先頭で、 `$display` 関数を用いて、波形表示する信号名をコンマ区切りで表示するようにしてください。1カラム目は横軸のラベルになります。複数ビットの信号は、信号名の後に `*` を付けてください。

例）`$display("time [ns],clk,rst_n,data*,data[2],data[1],data[0]");`

`$monitor` 関数を用いて、波形表示する信号の値を表示するようにしてください。1カラム目は `$realtime` で時刻を表示してください。

例）`$monitor("%t,%b,%b,%d,%b,%b,%b", $realtime, clk, rst_n, data, data[2], data[1], data[0]);`

ログの出力例を <<list:logForMatplotlib>> に示します。

[[list:logForMatplotlib]]
.Matplotlib でグラフを描く場合の、ログ出力例
----
time [ns],clk,rst_n,data*,data[2],data[1],data[0]
                   0,1,0,0,0,0,0
                   5,0,0,0,0,0,0
                  10,1,1,0,0,0,0
                  15,0,1,0,0,0,0
                  20,1,1,1,0,0,1
                  25,0,1,1,0,0,1
                  30,1,1,2,0,1,0
                  35,0,1,2,0,1,0
                  40,1,1,3,0,1,1
                  45,0,1,3,0,1,1
                  50,1,1,z,z,z,z
                  55,0,1,z,z,z,z
                  60,1,1,x,x,x,x
                  65,0,1,x,x,x,x
                  70,1,1,0,0,0,0
                  75,0,1,0,0,0,0
                  80,1,1,1,0,0,1
                  85,0,1,1,0,0,1
                  90,1,1,2,0,1,0
                  95,0,1,2,0,1,0
                 100,1,1,3,0,1,1
                 105,0,1,3,0,1,1
                 110,1,1,z,z,z,z
----

### WaveDrome でグラフを描く場合

WaveDrome で波形を描く場合、クロックサイクルベースの波形となります。クロック信号（デフォルトでは `clk`）が必要で、遅延は無視されます。

initial ブロックの先頭で、 `$display` 関数を用いて、波形表示する信号名をコンマ区切りで表示するようにしてください。1カラム目は無視されます。複数ビットの信号は、信号名の後に `*` を付けてください。

例）`$display("time [ns],clk,rst_n,data*,data[2],data[1],data[0]");`

クロックの立ち上がりで、`$strobe` 関数を用いて、波形表示する信号の値を表示するようにしてください。1カラム目は無視されます。

例）`always @(posedge clk) $strobe("%t,%b,%b,%d,%b,%b,%b", $realtime, clk, rst_n, data, data[2], data[1], data[0]);`

ログの出力例を <<list:logForMatplotlib>> に示します。

[[list:logForMatplotlib]]
.Matplotlib でグラフを描く場合の、ログ出力例
----
time [ns],clk,rst_n,data*,data[2],data[1],data[0]
                   0,1,0,0,0,0,0
                  10,1,1,0,0,0,0
                  20,1,1,1,0,0,1
                  30,1,1,2,0,1,0
                  40,1,1,3,0,1,1
                  50,1,1,z,z,z,z
                  60,1,1,x,x,x,x
                  70,1,1,0,0,0,0
                  80,1,1,1,0,0,1
                  90,1,1,2,0,1,0
                 100,1,1,3,0,1,1
                 110,1,1,z,z,z,z
----